"""
Plot treatment vs control behavior as line plots with weekly time periods.

Replaces the bar-plot comparison with dots connected by lines and std shading.
- t=0: during-closure (single period)
- Pre: t=-n_weeks,...,-1 (one week each)
- Post: t=1,...,n_weeks (one week each)
- Metrics: n_purchases per week, new_product_ratio, total_discount, coupon_usage_rate
"""

import sys
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from analyze_closure_impact import (
    CLOSURES_CSV,
    DEFAULT_LOWEST_PURCHASES,
    DEFAULT_LOWEST_RATIO,
    MIN_CTRL_TREAT_RATIO,
    MIN_GROUP_SIZE,
    OUTPUT_DIR,
    OUTPUT_CUSTOMER_STORE_DIR,
    USE_SET_UP_TIME_MATCHED_CONTROL,
    build_date_sorted_index,
    get_treatment_and_control_members_for_closure,
    get_customer_store_preference,
    load_order_commodity_data,
    load_order_result_data,
)
from analyze_closure_impact import _compute_customer_behavior, _slice_by_date

# Metrics to plot: (column_name, y_label, is_per_week)
METRICS = [
    ("n_purchases_per_week", "Purchases per Week", True),
    ("new_product_ratio", "New Product Ratio", False),
    ("total_discount", "Mean Total Discount", False),
    ("coupon_usage_rate", "Coupon Usage Rate", False),
]


PAIR_REGISTRY_CSV = OUTPUT_CUSTOMER_STORE_DIR / "closure_pair_registry.csv"


def _pair_key(dept_id: int, closure_start: str) -> tuple[int, str]:
    return int(dept_id), pd.to_datetime(closure_start).strftime("%Y-%m-%d")


def _parse_control_store_ids(serialized: object) -> List[int]:
    if serialized is None or (isinstance(serialized, float) and np.isnan(serialized)):
        return []
    s = str(serialized).strip()
    if not s:
        return []
    return [int(x) for x in s.split("|") if x != ""]


def load_kept_registry_rows() -> Dict[tuple[int, str], pd.Series]:
    """Load closure_pair_registry.csv and return kept rows keyed by (dept_id, closure_start)."""
    if not PAIR_REGISTRY_CSV.exists():
        raise FileNotFoundError(
            f"Missing pair registry: {PAIR_REGISTRY_CSV}. "
            "Run analyze_closure_impact.py first to generate closure_pair_registry.csv."
        )

    registry = pd.read_csv(PAIR_REGISTRY_CSV, encoding="utf-8-sig")
    required_cols = {"dept_id", "closure_start", "status", "control_store_ids"}
    missing = required_cols - set(registry.columns)
    if missing:
        raise ValueError(
            f"Invalid pair registry at {PAIR_REGISTRY_CSV}: missing columns {sorted(missing)}"
        )

    kept = registry[registry["status"] == "kept"].copy()
    if kept.empty:
        raise ValueError(
            f"No kept rows found in {PAIR_REGISTRY_CSV}. "
            "Run analyze_closure_impact.py and ensure closures pass screening."
        )

    rows_map: Dict[tuple[int, str], pd.Series] = {
        _pair_key(int(r["dept_id"]), r["closure_start"]): r
        for _, r in kept.iterrows()
    }
    return rows_map


def build_week_level_panel(
    df_commodity: pd.DataFrame,
    df_order: pd.DataFrame,
    closures: pd.DataFrame,
    customer_preference: pd.DataFrame,
    window_weeks: int,
    lowest_purchases: int,
    lowest_ratio: float,
    use_set_up_time_matched_control: bool = False,
) -> pd.DataFrame:
    """
    Build panel with one row per (closure, group, t, member_id)
    where t in {-n_weeks,...,-1, 0, 1,..., n_weeks}.
    t=0 is during-closure; t<0 are pre weeks; t>0 are post weeks.
    Pairing is loaded from closure_pair_registry.csv (generated by analyze_closure_impact).
    No on-the-fly pair construction is performed here.
    """
    if not use_set_up_time_matched_control:
        raise ValueError(
            "plot_closure_trend.py requires set-up-time matched control via pair registry. "
            "Set USE_SET_UP_TIME_MATCHED_CONTROL=True."
        )

    df_com_s = build_date_sorted_index(df_commodity)
    df_ord_s = build_date_sorted_index(df_order)
    unique_visits = df_commodity[["member_id", "date", "dept_id"]].drop_duplicates()

    registry_rows = load_kept_registry_rows()

    rows: List[Dict] = []
    n_closures = len(closures)
    for idx, (_, closure) in enumerate(closures.iterrows()):
        if (idx + 1) % 20 == 0 or idx == 0:
            print(f"    Processing closure {idx + 1}/{n_closures}...")
        dept_id = int(closure["dept_id"])
        closure_start = pd.to_datetime(closure["closure_start"])
        closure_end = pd.to_datetime(closure["closure_end"])
        closure_duration = max(int(closure["closure_duration_days"]), 1)

        reg_key = _pair_key(dept_id, closure["closure_start"])
        reg_row = registry_rows.get(reg_key)
        if reg_row is None:
            print(f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): not found as kept in closure_pair_registry.csv.")
            continue

        control_store_ids = _parse_control_store_ids(reg_row["control_store_ids"])
        if not control_store_ids:
            print(f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): empty control_store_ids in closure_pair_registry.csv.")
            continue

        treatment, closure_control, _ = get_treatment_and_control_members_for_closure(
            unique_visits=unique_visits,
            customer_preference=customer_preference,
            closure=closure,
            lowest_purchases=lowest_purchases,
            lowest_ratio=lowest_ratio,
            use_set_up_time_matched_control=True,
            control_pool=None,
            control_stores_by_closure={(dept_id, closure["closure_start"]): control_store_ids},
        )

        if not treatment:
            print(f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): no qualified treatment members.")
            continue
        if not closure_control:
            msg = f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): no qualified control members."
            if use_set_up_time_matched_control:
                msg += f" (control_stores={control_store_ids})"
            print(msg)
            continue

        if len(treatment) < MIN_GROUP_SIZE or len(closure_control) < MIN_GROUP_SIZE:
            print(f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): #treatment={len(treatment)} or #control={len(closure_control)} < {MIN_GROUP_SIZE}.")
            continue

        dur_start = closure_start.date()
        dur_end = closure_end.date()
        during_slice = _slice_by_date(df_com_s, dur_start, dur_end)
        during_purch = during_slice[["member_id"]].drop_duplicates()
        t_rate = during_purch["member_id"].isin(treatment).sum() / len(treatment)
        c_rate = during_purch["member_id"].isin(closure_control).sum() / len(closure_control)
        if c_rate < MIN_CTRL_TREAT_RATIO * t_rate:
            print(f"    Skipping closure (dept_id={dept_id}, closure_start={closure['closure_start']}): ctrl_rate={c_rate:.3f} < {MIN_CTRL_TREAT_RATIO}*treat_rate={t_rate:.3f}.")
            continue

        for group_label, members in [("treatment", treatment), ("control", closure_control)]:
            if not members:
                continue

            # Pre weeks: t = -n_weeks, ..., -1
            for w in range(-window_weeks, 0):
                t = w
                start = (closure_start + pd.Timedelta(days=7 * w)).date()
                end = (closure_start + pd.Timedelta(days=7 * w + 6)).date()
                cust_df = _compute_customer_behavior(
                    df_com_s, df_ord_s, members, start, end, period_length_days=7
                )
                cust_df["dept_id"] = dept_id
                cust_df["group"] = group_label
                cust_df["t"] = t
                rows.append(cust_df)

            # During: t = 0
            dur_start = closure_start.date()
            dur_end = closure_end.date()
            cust_df = _compute_customer_behavior(
                df_com_s, df_ord_s, members, dur_start, dur_end,
                period_length_days=closure_duration,
            )
            cust_df["dept_id"] = dept_id
            cust_df["group"] = group_label
            cust_df["t"] = 0
            rows.append(cust_df)

            # Post weeks: t = 1, ..., n_weeks
            for w in range(1, window_weeks + 1):
                t = w
                start = (closure_end + pd.Timedelta(days=7 * (w - 1) + 1)).date()
                end = (closure_end + pd.Timedelta(days=7 * w)).date()
                cust_df = _compute_customer_behavior(
                    df_com_s, df_ord_s, members, start, end, period_length_days=7
                )
                cust_df["dept_id"] = dept_id
                cust_df["group"] = group_label
                cust_df["t"] = t
                rows.append(cust_df)

    panel = pd.concat(rows, ignore_index=True)

    # Convert n_purchases (per day) to n_purchases_per_week = n_purchases * 7
    panel["n_purchases_per_week"] = panel["n_purchases"] * 7

    return panel


def aggregate_by_group_t(panel: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate to (group, t): mean and std over all (member_id, closure) rows.
    """
    metrics = ["n_purchases_per_week", "new_product_ratio", "total_discount", "coupon_usage_rate"]
    agg_dict = {}
    for m in metrics:
        if m in panel.columns:
            agg_dict[m] = ["mean", "std"]
    if not agg_dict:
        return pd.DataFrame()

    agg = panel.groupby(["group", "t"]).agg(agg_dict).reset_index()
    # Flatten MultiIndex columns: (metric, agg) -> "metric_agg"
    new_cols = []
    for c in agg.columns:
        if isinstance(c, tuple) and len(c) == 2:
            new_cols.append(f"{c[0]}_{c[1]}" if c[1] else c[0])
        else:
            new_cols.append(c)
    agg.columns = new_cols
    return agg


def plot_trend_lines(
    agg: pd.DataFrame,
    window_weeks: int,
    output_path: Path,
) -> None:
    """
    Plot all metrics in a combined figure: line + dots + std shading.
    Two lines per subplot: treatment and control.
    """
    t_vals = sorted(agg["t"].unique())
    n_metrics = len(METRICS)
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    axes = axes.flatten()

    colors = {"treatment": "#d62728", "control": "#1f77b4"}

    for ax, (metric_col, metric_label, _) in zip(axes, METRICS):
        mean_col = f"{metric_col}_mean"
        std_col = f"{metric_col}_std"

        if mean_col not in agg.columns or std_col not in agg.columns:
            continue

        for group in ["treatment", "control"]:
            sub = agg[agg["group"] == group].sort_values("t")
            if sub.empty:
                continue
            x = sub["t"].values
            y = sub[mean_col].values
            std = sub[std_col].values
            std = np.where(np.isnan(std), 0, std)

            ax.plot(x, y, "o-", color=colors[group], linewidth=2, markersize=6, label=group.capitalize())
            ax.fill_between(x, y - std, y + std, color=colors[group], alpha=0.2)

        ax.axvline(x=0, color="gray", linestyle="--", alpha=0.6)
        ax.set_xlabel("Period t (0 = during closure)", fontsize=10)
        ax.set_ylabel(metric_label, fontsize=10)
        ax.set_title(metric_label, fontsize=11, fontweight="bold")
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.set_xticks(t_vals)

    fig.suptitle(
        f"Treatment vs Control: Behavior Across Closure Periods\n"
        f"(window = {window_weeks} weeks, mean ± std over customers and closures)",
        fontsize=12, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {output_path}")


def main(limit_closures: int | None = None):
    """Run with: python plot_closure_trend.py > plot_closure_trend.log 2>&1"""
    print("=" * 60)
    print("Closure Trend Line Plots (weekly periods)")
    print("=" * 60)

    df = load_order_commodity_data()
    df_order = load_order_result_data()
    closures = pd.read_csv(CLOSURES_CSV, encoding="utf-8-sig")
    if limit_closures:
        closures = closures.head(limit_closures)
        print(f"\nLoaded {len(closures)} closures (limited for quick test).")
    else:
        print(f"\nLoaded {len(closures)} closures.")
    print(f"  Control: use_set_up_time_matched_control={USE_SET_UP_TIME_MATCHED_CONTROL}")

    customer_preference = get_customer_store_preference(df, lowest_purchases=DEFAULT_LOWEST_PURCHASES)

    for window_weeks in [2, 4, 8]:
        print(f"\n--- Building panel for {window_weeks}-week window ---")
        panel = build_week_level_panel(
            df, df_order, closures, customer_preference,
            window_weeks=window_weeks,
            lowest_purchases=DEFAULT_LOWEST_PURCHASES,
            lowest_ratio=DEFAULT_LOWEST_RATIO,
            use_set_up_time_matched_control=USE_SET_UP_TIME_MATCHED_CONTROL,
        )
        print(f"  Panel rows: {len(panel):,}")

        agg = aggregate_by_group_t(panel)
        print(f"  (group, t) combinations: {len(agg)}")

        out_path = OUTPUT_DIR / f"closure_trend_lines_w{window_weeks}.pdf"
        plot_trend_lines(agg, window_weeks, out_path)

    print("\nDone.")


if __name__ == "__main__":
    import sys
    limit = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else None
    main(limit_closures=limit)
